version: '3.8'

services:
  db:
    image: postgres:13.2
    container_name: gotham-database
    restart: always
    ports:
      - "5432:5432"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      PGUSER: ${PG_USER}
      PGPASSWORD: ${PG_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
  api:
    build:
      # a changer une fois merged (./api)
      context: ./gotham_city_app
    environment:
        PGUSER: ${PG_USER}
        PGPASSWORD: ${PG_PASSWORD}
        PGDATABASE: ${PG_DATABASE}
        PGPORT: ${PG_PORT}
        PGHOST: ${PG_HOST}
    ports:
      - '4000:4000'
    depends_on:
      - db
  web:
    build:
      # a changer une fois merged (./web)
      context: ./gotham_city_interface
    ports:
      - '8080:8080'
volumes:
  pgdata:
