version: '3.8'

services:
  db:
    image: postgres:13.2
    container_name: gotham-database
    restart: always
    ports:
      - "5432:5432"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
  api:
    build:
      # a changer une fois merged (./api)
      context: ./gotham_city_app
    env_file:
      - gotham_city.env
    ports:
      - '4000:4000'
    depends_on:
      - db
  web:
    build:
      # a changer une fois merged (./web)
      context: ./gotham_city_interface      
    ports:
      - '8080:8080'
volumes:
  pgdata:
