version: '3.8'

services:
  db:
    image: postgres:13.2
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      PGUSER: postgres
      PGPASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
    networks:
      - timemanager
  gotham_city_app:
    build:
      context: ./api
    environment:
        PGUSER: ${PG_USER}
        PGPASSWORD: ${PG_PASSWORD}
        PGDATABASE: ${PG_DATABASE}
        PGPORT: ${PG_PORT}
        PGHOST: ${PG_HOST}
    ports:
      - '4000:4000'
    depends_on:
      - db
    networks:
      - timemanager
  gotham_city_interfaces:
    build:
      context: ./web
    environment:
      BACKEND_URL: ${BACKEND_URL}
    ports:
      - '80:8080'
volumes:
  pgdata:
networks:
  timemanager:
