import Config


# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :gotham_city, GothamCityWeb.Endpoint,
  load_from_system_env: true,
  http: [port: 4000],
  url: [host: "localhost", port: 4000],
  cache_static_manifest: "priv/static/cache_manifest.json"

# Configure your database connection
config :gotham_city, GothamCity.Repo,
       username: "postgres",
       password: "postgres",
       database: "gotham_city_dev",
       hostname: "localhost",
       stacktrace: true,
       show_sensitive_data_on_connection_error: true,
       pool_size: 10

config :gotham_city, GothamCityWeb.Endpoint,
       # Binding to loopback ipv4 address prevents access from other machines.
       # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
       http: [ip: {0, 0, 0, 0}, port: 4000],
       check_origin: false,
       code_reloader: false,
       debug_errors: true,
       secret_key_base: "Pctw+u5euohYlM/CCZsxfKDTx/7fFJrufOgAsiDlvT1uhYDXZHgo1pD4s04v6E5g",
       watchers: [
         esbuild: {Esbuild, :install_and_run, [:default, ~w(--sourcemap=inline --watch)]},
         tailwind: {Tailwind, :install_and_run, [:default, ~w(--watch)]}
       ]

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: GothamCity.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
